name: release
on:
  push:
    branches: [main]
    tags: ["v*.*.*"]

env:
  PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
  PGP_SECRET: ${{ secrets.PGP_SECRET }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

jobs:
  publish:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ openjdk@1.17.0 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: ${{ matrix.java }}
      - uses: olafurpg/setup-gpg@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-coursier-${{ hashFiles('build.sbt') }}-${{ hashFiles('project/*.scala') }}
          restore-keys: ${{ runner.os }}-coursier-
      - name: Cache .sbt
        uses: actions/cache@v3
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('build.sbt') }}-${{ hashFiles('project/*.scala') }}
          restore-keys: ${{ runner.os }}-sbt-
      - name: Publish
        run: sbt clean ci-release
